name: C/C++ CI

on:
  pull_request:
    branches: [ "main","dev" ]
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    env:
     CC: clang
     CFLAGS: -Werror
    steps:
    # temp code from: https://github.com/glfw/glfw/blob/dc557ecf38a42b0b93898a7aef69f6dc48bf0e57/.github/workflows/build.yml
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev

    - name: Configure Null shared library
      run: cmake -B build-null-shared -D GLFW_BUILD_WAYLAND=OFF -D GLFW_BUILD_X11=OFF -D BUILD_SHARED_LIBS=ON
    - name: Build Null shared library
      run: cmake --build build-null-shared --parallel

    - name: Configure X11 shared library
      run: cmake -B build-x11-shared -D GLFW_BUILD_WAYLAND=OFF -D GLFW_BUILD_X11=ON -D BUILD_SHARED_LIBS=ON
    - name: Build X11 shared library
      run: cmake --build build-x11-shared --parallel

    - name: Configure Wayland shared library
      run: cmake -B build-wayland-shared -D GLFW_BUILD_WAYLAND=ON -D GLFW_BUILD_X11=OFF -D BUILD_SHARED_LIBS=ON
    - name: Build Wayland shared library
      run: cmake --build build-wayland-shared --parallel

    - name: Configure Wayland+X11 static library
      run: cmake -B build-full-static -D GLFW_BUILD_WAYLAND=ON -D GLFW_BUILD_X11=ON
    - name: Build Wayland+X11 static library
      run: cmake --build build-full-static --parallel

    - name: Configure Wayland+X11 shared library
      run: cmake -B build-full-shared -D GLFW_BUILD_WAYLAND=ON -D BUILD_SHARED_LIBS=ON -D GLFW_BUILD_X11=ON
    - name: Build Wayland+X11 shared library
      run: cmake --build build-full-shared --parallel
    - name: Send a request to webhook
      run: |
        RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
        "username": "GitHub",
        "content": "@everyone",
        "embeds": [
          {
            "type": "rich",
            "title": "New Changes",
            "description": "New changes on DroneGPS repository by ${{ github.actor }}",
            "color": 2123412,
            "thumbnail": {
              "url": "https://avatars.githubusercontent.com/u/160980408?v=4"
            },
            "author": {
              "name": "${{ github.actor }}",
              "url": "https://github.com/${{ github.actor_id }}",
              "icon_url": "https://avatars.githubusercontent.com/u/${{ github.actor_id }}?v=4"
            },
            "url": "https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"

          }
        ]
        }' ${{ secrets.WEBHOOK_URL }})
        echo "Webhook server response: $RESPONSE"
