name: C/C++ CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
    - uses: actions/checkout@v4

    # Setup Visual Studio environment
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
